"""Update Campaign model

Revision ID: be3f6015186f
Revises: f7a9439c639f
Create Date: 2026-06-11 23:34:22.664747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3f6015186f'
down_revision: Union[str, Sequence[str], None] = 'f7a9439c639f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('segment_id', sa.String(length=36), nullable=False))
    op.add_column('campaigns', sa.Column('goal', sa.String(length=255), nullable=False))
    op.add_column('campaigns', sa.Column('channel', sa.String(length=50), nullable=False))
    op.add_column('campaigns', sa.Column('subject_line', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('message_body', sa.String(), nullable=False))
    op.create_index(op.f('ix_campaigns_segment_id'), 'campaigns', ['segment_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'segments', ['segment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_segment_id'), table_name='campaigns')
    op.drop_column('campaigns', 'message_body')
    op.drop_column('campaigns', 'subject_line')
    op.drop_column('campaigns', 'channel')
    op.drop_column('campaigns', 'goal')
    op.drop_column('campaigns', 'segment_id')
    # ### end Alembic commands ###
